theme: jekyll-theme-minimal
title: "Amy Gaffney: Data Analyst"
description: "A passionate data storyteller."
# Sidebar / site links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/-amygaffney/
    icon: linkedin
