theme: jekyll-theme-minimal

title: "Amy Gaffney"
description: "Business Data Analyst focused on data storytelling, visualization, and business intelligence."

logo: /assets/headshot.jpg

github_username: agaffney-hub

social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/-amygaffney/
    icon: linkedin

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
